# Generated by Django 2.2.7 on 2020-02-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureURL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureurl',
            name='action',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pictureurl',
            name='auid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
