# Generated by Django 2.2.7 on 2020-03-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureURL', '0004_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='csv_file_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
