# Generated by Django 2.2.7 on 2020-03-06 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictureURL', '0006_auto_20200306_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureurl',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to=settings.AUTH_USER_MODEL),
        ),
    ]
