# Generated by Django 2.2.7 on 2020-03-10 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictureURL', '0008_auto_20200306_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='campaign_url',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='pictureURL.Pictureurl'),
        ),
        migrations.CreateModel(
            name='FacebookStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=255)),
                ('publish_timestamp', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Facebook Statuses',
                'ordering': ['publish_timestamp'],
            },
        ),
    ]
